name: Wyte URL to APK Builder

on:
  workflow_dispatch:
    inputs:
      app_url:
        description: 'Website URL to convert'
        required: true
        type: string
      app_name:
        description: 'App Name'
        required: true
        type: string

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install PWABuilder
        run: npm install -g @pwabuilder/pwabuilder-cli

      - name: Generate APK
        run: |
          pwabuilder ${{ inputs.app_url }} --platform android --name "${{ inputs.app_name }}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app_name }}.apk
          path: ./dist/*.apk
